#ifndef _XTIMER_CONFIG_H
#define _XTIMER_CONFIG_H

#include "xparameters.h"

#define XSLEEPTIMER_IS_AXITIMER
#define XSLEEPTIMER_DEVICEID XPAR_AXI_TIMER_0_DEVICE_ID
#define XTIMER_NO_TICK_TIMER

#endif /* XTIMER_CONFIG_H */
