# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/deulamco/Documents/echo_server/echo_server.srcs/sources_1/bd/system/ip/system_ilmb_v10_0/system_ilmb_v10_0.xci
# IP: The module: 'system_ilmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/deulamco/Documents/echo_server/echo_server.gen/sources_1/bd/system/ip/system_ilmb_v10_0/system_ilmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/deulamco/Documents/echo_server/echo_server.srcs/sources_1/bd/system/ip/system_ilmb_v10_0/system_ilmb_v10_0.xci
# IP: The module: 'system_ilmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/deulamco/Documents/echo_server/echo_server.gen/sources_1/bd/system/ip/system_ilmb_v10_0/system_ilmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
